export {default as About } from './about/About'
export {default as Catalog } from './catalog/Catalog'
export {default as Footer } from './footer/Footer'
export {default as Header } from './header/Header'
export {default as News } from './news/News'
export {default as Partners } from './partners/Partners'
export {default as Products } from './products/Products'